### ISSUE TITLE
Enable Windows 7, 10 32/64 execution

### ISSUE THREAD

**Issue by raistlinJ** [ARL-UTEP-OC/ecel#27]
Use virtualenv
Test with all plugins (except snoopy, which is Linux-only)

**Comment by kpkeenan** [comment]
ECEL can now be set to run on start up, with this bug:  Nmap/Tshark might not work since they might not be added to %PATH%.

**Comment by kpkeenan** [comment]
Functional on Windows 7 32-bit, 8/10 64-bit. See caveats and additional installation instructions in the README.
