### ISSUE TITLE
Create a windows installer

### ISSUE THREAD

**Issue by raistlinJ** [ARL-UTEP-OC/ecel#29]
-Maximize the usage of pip. 
-Make sure virtualenv is used.
-Mimic the install script for EmuBox here: [https://github.com/ARL-UTEP-OC/emubox/blob/master/install.bat]

**Comment by kpkeenan** [comment]
Main GUI window runs, but crashes.

**Comment by kpkeenan** [comment]
Main GUI window runs. (with behavioral bugs).  64 bit windows 10, python 2.7
